language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
services:
  - xvfb
addons:
    chrome: stable
before_script:
  - npm install -g @angular/cli
script:
  - npm run test
  - ng build --output-path dist/angular-todo --base-href https://bubblekid.github.io/angular-todo
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: angular-todo-mark

